### PR TITLE
README: Fix setup instruction rendering

### PR DESCRIPTION
**Pull request by Turbo87**

### CODE REVIEW

**Comment by gewesp** [comment]
Fixed

**Comment by Turbo87** [comment]
any reason for not merging this and rewriting the commit?

**Comment by gewesp** [comment]
Yes.  My inability to comprehend github :)

On Thu, Oct 29, 2015 at 10:20 AM, Tobias Bieniek <notifications@github.com>
wrote:

> any reason for not merging this and rewriting the commit?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gewesp/cpp-lib/pull/1#issuecomment-152124037>.
>



-- 
Gerhard Wesp / KISS Technologies
http://www.kisstech.ch/ktrax/
+41 (0)79 137 18 70

**Comment by Turbo87** [comment]
alright :D

**Comment by Turbo87** [comment]
let me know when you need help. happy to explain stuff.

**Comment by gewesp** [comment]
Thanks, will be in touch!

On Thu, Oct 29, 2015 at 10:29 AM, Tobias Bieniek <notifications@github.com>
wrote:

> let me know when you need help. happy to explain stuff.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gewesp/cpp-lib/pull/1#issuecomment-152126078>.
>



-- 
Gerhard Wesp / KISS Technologies
http://www.kisstech.ch/ktrax/
+41 (0)79 137 18 70

**Pull request closed without merging**
